# standard jekyll configuration

permalink: /:year/:month/:title/
exclude: ['readme.md', 'Rakefile', 'Procfile', 'config.rb', '.gitignore', '.sass-cache', 'Gemfile', 'Gemfile.lock']
show_drafts: true

title: Scholars' Lab Slides
domain: http://slides.scholarslab.org
